import { Request, Response } from 'express'
import { AppError } from '@/utils/errors'
import { validateChronicConditionCreation } from '@/schemas/dashboard/medicalData/chronicCondition'
import { ChronicConditionModel } from '@/models/Dashboard/MedicalData/ChronicCondition'

export class DashboardChronicConditionController {
  private model: typeof ChronicConditionModel

  constructor({ model }: { model: typeof ChronicConditionModel }) {
    this.model = model
  }

  create = async (req: Request, res: Response): Promise<void> => {
    try {
      const { patientDataPk } = req.params
      const result = validateChronicConditionCreation(req.body)

      if (!result.success || !result.data) {
        res.status(400).json({ error: JSON.parse(result.error.message) })
        return
      }

      const newObject = await this.model.create({ patientDataPk, data: result.data })
      res
        .status(201)
        .send({ condition: newObject, message: 'Condici贸n cr贸nica registrada correctamente' })
    } catch (error) {
      if (error instanceof AppError) {
        res.status(error.statusCode).json({ error: error.message })
      }
      res.status(500).json({ error: 'Internal server error' })
    }
    return
  }

  delete = async (req: Request, res: Response) => {
    const { pk } = req.params

    try {
      const deletedObject = await this.model.delete({ pk })
      res.send({ condition: deletedObject, message: 'Condici贸n cr贸nica eliminada correctamente' })
    } catch (error) {
      if (error instanceof AppError) {
        res.status(error.statusCode).json({ error: error.message })
        return
      }
      res.status(500).json({ error: 'Internal server error' })
    }
  }
}
